### ISSUE TITLE
Mishandling of Cats Games

### ISSUE THREAD

**Issue by AusIV** [cstringer/MetaTicTacToe#1]
This game doesn't handle cats games, either in smaller boards, or in the metagame.

In the metagame, it's not a big deal. It just doesn't have an end-game sequence when you finish.

In the smaller boards, it's a problem. If you get a cat's game on a board, then your opponent forces you to play on a cat's gamed board, the game forces you to play on the board, but since the board is filled up you can't play. It should treat a cat's game as a completed game with no winner.

I discovered this when a metagame ended up as a cat's game, and I decided to see what happened when a sub-game came up as a cat's game. I had to play somewhat pathologically to get a cat's game to come up without filling up all of the corresponding spots on the other subgames, but it is possible. I doubt it would come up often during normal game play.

Also, good work on the implementation. It's very slick.

**Comment by cstringer** [comment]
ah! good catch – have to add an extra state/class for a completed, but tied board. so, how's the websockets implementation coming? ;) i'm studying up on implementing a MCTS algorithm for a little AI action in the meantime!
